{% set name = "hpccm" %}
{% set version = "20.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ff2cfe4f4472ae7b5920671b7339c81ae6ad50bb39fab23cb7f20be568ae48d7

build:
  number: 0
  entry_points:
    - hpccm=hpccm.cli:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - enum34  # [py<34]
    - pip
    - python
    - six
  run:
    - enum34  # [py<34]
    - python
    - six

test:
  imports:
    - hpccm
    - hpccm.building_blocks
    - hpccm.primitives
    - hpccm.templates
  commands:
    - hpccm --help

about:
  home: https://github.com/NVIDIA/hpc-container-maker
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: HPC Container Maker
  doc_url: https://github.com/NVIDIA/hpc-container-maker/tree/master/docs
  dev_url: https://github.com/NVIDIA/hpc-container-maker

extra:
  recipe-maintainers:
    - tschoonj
