{% set name = "hpccm" %}
{% set version = "25.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0065643f7ed5ec01983919f4eb1e8ca3eeafab2fefa63cb2d68a036dc7558850

build:
  number: 0
  entry_points:
    - hpccm=hpccm.cli:main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - six
    - setuptools
  run:
    - archspec
    - python >={{ python_min }}
    - six
    - packaging

test:
  requires:
    - python {{ python_min }}
  imports:
    - hpccm
    - hpccm.building_blocks
    - hpccm.primitives
    - hpccm.templates
  commands:
    - hpccm --help

about:
  home: https://github.com/NVIDIA/hpc-container-maker
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: HPC Container Maker
  doc_url: https://github.com/NVIDIA/hpc-container-maker/tree/master/docs
  dev_url: https://github.com/NVIDIA/hpc-container-maker

extra:
  recipe-maintainers:
    - tschoonj
