{% set name = "hpccm" %}
{% set version = "21.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 37b1ab1c4f680d67e9916350842f3a1de7e6e8c75754a21cd05bab4e0e0b0f12

build:
  number: 0
  entry_points:
    - hpccm=hpccm.cli:main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - pip
    - python >=3.4
    - six
  run:
    - python >=3.4
    - six

test:
  imports:
    - hpccm
    - hpccm.building_blocks
    - hpccm.primitives
    - hpccm.templates
  commands:
    - hpccm --help

about:
  home: https://github.com/NVIDIA/hpc-container-maker
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: HPC Container Maker
  doc_url: https://github.com/NVIDIA/hpc-container-maker/tree/master/docs
  dev_url: https://github.com/NVIDIA/hpc-container-maker

extra:
  recipe-maintainers:
    - tschoonj
