travis:
  secure:
    BINSTAR_TOKEN: sLt/ToN+uhaNsexqIe4dbkTl9fO00QWaB8ILkjAN5mqu2b6t92wi7GIsjskl2HIziKSOGJo7erWUkB4CpjtQoKxSoy0CMsgtfFNf92XqYo3usH/9fS3fIbxmnceDIv1fOW/QAcKrnXKvXmMjBbiOUzIbnSRyvjRzCilhq/F0P8lCwAAml+zVarIiAFi8MChgwuoO0YddKHBYKX/WQ8RS0sdSgiLAjNGpGc3zszuUKOEX32XN7qJCRWdZ8mCol/h663MGgVtjmqZq7JFimTBPMGjMzkp/dZ66LvQpAfajnxarNzGmSfvcni914jVmYKyWPC1W0G9vS7j9U5mlR4HtydaZCBfKES9aOKN3SuCSdnoVTcVLCfRMOSU63AE2qS9GGoxQIPe664QRle2WX/JWLL6FbMjMysH3x0Q/TW1MkV6y8EERrwT4E7aJqQD2KKL/Z5fVnzsonsQ7lVsD1m3XwyEUy6DQVuQ4Cutsnoox1zijm7Y2149GnXju0tfwKUF0Xr3Qyf+rFLwuc4BfboQr8crnCforhFOIMgLuPkqxdL4mnQMe8EqSk5zFxmXjZbTI9BFNAL0UrdjZ+ke55XR3yvNl5DhW+A4nyzmTKQnE/yNuSdXQDD21kvYUggiwwlC8CG8ht7KX6Sxwe1UwtT/0+ZOkxlCtWmPuFoWChRnGlSE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
