travis:
  secure:
    BINSTAR_TOKEN: HuLhaB16ZXwC7dlCenyDCMobaP23r9g4dIoUVrlDPvnaB04Cjt450MTbR6vX5hjwbTmVqY3fU8qmxjO5asXhL53WorGs4UlvqMjioZm+FAdnUXthh7obnqBRG3W7u96mLoLBNnoJciKR0Geagtgm1bP7M2jErLrcT1mpNfaF4fOpmmPzcmkOn0VKPlu/8DZVyl/66wQZ7Hu/L/phnK7iwW9viTbOs0LVmdPEZZ/Swg929MQc5Jt8W60g0CaW86RUKwNgsXclVKJpxpSQvlT1AiSRQHvTv9Q2PYqntijv69CZsPk06yA4F2t92KRTTTLpPCdHFgCp9ymQOGitTHlPYkzHtAlcXiKLwKMxEXlbwwdkBcEE4P303Bczz0MRXcFm6WdGOPCcwQEsEGPwFQbtqGSTIiLAh5fpgijKcB3j85pHq3sPrOcg1U1Bxf6ZOUj1dWSKJsGd/zgmbbwWVxISZiksTXy/95GONFnwuJBx8v8rmnTHe5xVrXEmEQRXNkyeiWz6mR6e2v7o1KHcNCnQEM0ZfGWONBfDUiUJI3eW2xpPEHrM1Vgk+bGvQHDpwsOneKuwkYHhE88lR9nhgo5aYl0lOITr9hzl7E8rw8yFDJItdVTBZXcpvnKxWpXofgnA91AotOfgqT3atAUmRE5rv1H0aMrdZ0RCM9/qmmJKy3w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
